services:
    # crud
    shapecode_crud.controller:
        class: Shapecode\Bundle\CRUDBundle\Controller\CrudController
        arguments:
            - '@shapecode_crud.execution'

    shapecode_crud.execution:
        class: Shapecode\Bundle\CRUDBundle\Cruding\Execution
        public: false
        arguments:
            - '@shapecode_crud.crud_organizer'
            - '@shapecode_crud.action_manager'
            - '@shapecode_crud.route_manager'
            - '@request_stack'
            - '@service_container'

    shapecode_crud.manager_factory:
        class: Shapecode\Bundle\CRUDBundle\Factory\ManagerFactory
        public: false
        arguments: ["@service_container"]

    shapecode_crud.crud_organizer:
        class: Shapecode\Bundle\CRUDBundle\Cruding\Organizer
        public: false
        arguments:
            - "@shapecode_crud.manager_factory"

    shapecode_crud.action_manager:
        class: Shapecode\Bundle\CRUDBundle\Cruding\ActionManager
        public: false
        arguments: ["@service_container"]

    shapecode_crud.route_manager:
        class: Shapecode\Bundle\CRUDBundle\Cruding\RouteManager
        public: false
        arguments: ["@router"]

    shapecode_crud.route_laoder.crud:
        class: Shapecode\Bundle\CRUDBundle\Routing\CrudLoader
        public: false
        arguments: ['@shapecode_crud.crud_organizer']
        tags:
            - { name: routing.loader }

    shapecode_crud.twig_extension.crud:
        class: Shapecode\Bundle\CRUDBundle\Twig\CRUDExtension
        public: false
        arguments: ['@translator']
        tags:
            - { name: twig.extension }
